"""
analysis.py
-----------
Regenerates the quantitative results reported in the paper
"Helping Educators Choose AI Tools" (ICL 2026) from one or more scores CSVs
produced by `run.py evaluate`.

It reproduces:
  - Table 3  : mean rubric scores per model (Correctness, Completeness,
               Clarity, Cognitive Alignment, Overall)
  - Table 4  : mean overall score per model x domain, with spread
  - Bloom-level means per model and the Higher-Order (L4-L6) mean
  - Difficulty x Bloom interaction cell means (Figure 4)
  - Two-way ANOVA on Overall ~ difficulty * bloom, reporting the
    interaction F and partial eta-squared for each factor (contribution 4)
  - BLEU range across non-MCQ responses

The scores CSVs are NOT shipped in the repo (they are regenerated by running
the pipeline against the six models). Point --scores at the file(s) you
produced, e.g.:

    python analysis.py --scores scores_gpt_gemini.csv scores_claude.csv \\
        scores_llama.csv scores_deepseek.csv

Requires: pandas, numpy, statsmodels (see requirements.txt).
"""

import argparse
import glob
import sys

import numpy as np
import pandas as pd

# Higher-order Bloom levels (Analyse, Evaluate, Create).
HIGHER_ORDER = {4, 5, 6}
DIMENSIONS = ["correctness", "completeness", "clarity", "cognitive_alignment"]


def load_scores(paths):
    """Load and concatenate one or more scores CSVs into a single frame."""
    frames = []
    for pattern in paths:
        for path in sorted(glob.glob(pattern)) or [pattern]:
            frames.append(pd.read_csv(path))
    if not frames:
        sys.exit("No scores files found.")
    df = pd.concat(frames, ignore_index=True)
    # Drop error rows and rows without an overall score.
    if "error" in df.columns:
        df = df[df["error"] != True]  # noqa: E712
    df = df.dropna(subset=["overall_score", "model_name"])
    return df


def table3_model_means(df):
    """Table 3: mean of each rubric dimension + overall, per model."""
    cols = DIMENSIONS + ["overall_score"]
    t = df.groupby("model_name")[cols].mean().round(2)
    return t.sort_values("overall_score", ascending=False)


def table4_domain_means(df):
    """Table 4: mean overall per model x domain, with per-domain spread."""
    t = df.pivot_table(index="model_name", columns="domain",
                       values="overall_score", aggfunc="mean").round(2)
    spread = (t.max(axis=0) - t.min(axis=0)).round(2)
    spread.name = "Spread"
    return t, spread


def bloom_means(df):
    """Mean overall per model x Bloom level, plus the Higher-Order (L4-L6) mean."""
    per_level = df.pivot_table(index="model_name", columns="bloom_level",
                              values="overall_score", aggfunc="mean").round(2)
    ho = (df[df["bloom_level"].isin(HIGHER_ORDER)]
          .groupby("model_name")["overall_score"].mean().round(2))
    ho.name = "HigherOrder_L4_L6"
    return per_level, ho


def difficulty_bloom_cells(df):
    """Figure 4: overall means for each difficulty x Bloom-group cell (all models)."""
    d = df.copy()
    d["bloom_group"] = np.where(d["bloom_level"].isin(HIGHER_ORDER),
                                "L4-6 Higher-Order",
                                "L" + d["bloom_level"].astype("Int64").astype(str))
    return d.pivot_table(index="difficulty", columns="bloom_group",
                         values="overall_score", aggfunc="mean").round(2)


def two_way_anova(df):
    """
    Two-way ANOVA: Overall ~ C(difficulty) * C(bloom_level).
    Returns a dict with the interaction F/p and partial eta-squared per term.
    """
    import statsmodels.formula.api as smf
    from statsmodels.stats.anova import anova_lm

    d = df.rename(columns={"overall_score": "overall"}).copy()
    d = d.dropna(subset=["overall", "difficulty", "bloom_level"])
    model = smf.ols("overall ~ C(difficulty) * C(bloom_level)", data=d).fit()
    aov = anova_lm(model, typ=2)

    ss_resid = aov.loc["Residual", "sum_sq"]
    out = {}
    for term in aov.index:
        if term == "Residual":
            continue
        ss = aov.loc[term, "sum_sq"]
        out[term] = {
            "F": round(float(aov.loc[term, "F"]), 2),
            "p": float(aov.loc[term, "PR(>F)"]),
            "partial_eta_sq": round(float(ss / (ss + ss_resid)), 3),
        }
    return out


def bleu_range(df):
    """BLEU min/max across non-MCQ responses, if the column is present."""
    if "bleu" not in df.columns:
        return None
    b = df["bleu"].dropna()
    b = b[b > 0] if (b > 0).any() else b
    if b.empty:
        return None
    return round(float(b.min()), 3), round(float(b.max()), 3)


def main():
    ap = argparse.ArgumentParser(description="Regenerate the paper's tables/stats.")
    ap.add_argument("--scores", nargs="+", required=True,
                    help="One or more scores CSV paths or globs.")
    args = ap.parse_args()

    df = load_scores(args.scores)
    print(f"Loaded {len(df):,} scored rows across "
          f"{df['model_name'].nunique()} models.\n")

    print("=" * 70)
    print("TABLE 3 — Mean rubric scores per model")
    print("=" * 70)
    print(table3_model_means(df).to_string())

    print("\n" + "=" * 70)
    print("TABLE 4 — Mean overall score by model x domain")
    print("=" * 70)
    t4, spread = table4_domain_means(df)
    print(t4.to_string())
    print("\nSpread (max-min per domain):")
    print(spread.to_string())

    print("\n" + "=" * 70)
    print("Bloom-level means per model (+ Higher-Order L4-L6 mean)")
    print("=" * 70)
    per_level, ho = bloom_means(df)
    print(per_level.to_string())
    print("\nHigher-Order (L4-L6) mean per model:")
    print(ho.to_string())

    print("\n" + "=" * 70)
    print("FIGURE 4 — Difficulty x Bloom interaction cell means")
    print("=" * 70)
    print(difficulty_bloom_cells(df).to_string())

    print("\n" + "=" * 70)
    print("Two-way ANOVA: Overall ~ difficulty * bloom_level")
    print("=" * 70)
    try:
        for term, stats in two_way_anova(df).items():
            print(f"{term:28s}  F={stats['F']:>8.2f}  "
                  f"p={stats['p']:.3g}  partial_eta_sq={stats['partial_eta_sq']}")
    except Exception as exc:  # statsmodels missing or singular design
        print(f"ANOVA skipped: {exc}")

    br = bleu_range(df)
    if br:
        print("\nBLEU range across non-MCQ responses: "
              f"{br[0]:.3f}–{br[1]:.3f}")


if __name__ == "__main__":
    main()